@base_url=http://localhost:8080
@prefix_path=todo

# @name auth
GET {{base_url}}/tokenz

###
@token = {{auth.response.body.$.token}}

###
# restcli --show body ./test/create_todo.http

POST {{base_url}}/{{prefix_path}}
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTk4ODYwNzJ9.u8lzwtTlhsEDZx0X5xLLLw0JyhOa_pOF1dhtW7xWObA

{
  "text": "task 2"
}